// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SalegaTech.Infrastructure.Database;

#nullable disable

namespace SalegaTech.Infrastructure.Database.Migrations
{
    [DbContext(typeof(ModernDbContext))]
    [Migration("20260413051000_InitialModern")]
    partial class InitialModern
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("SalegaTech.Domain.Entities.CreditFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PartnerId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SimulationId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FileCode")
                        .IsUnique();

                    b.HasIndex("PartnerId");

                    b.HasIndex("SimulationId");

                    b.ToTable("CreditFiles", (string)null);
                });

            modelBuilder.Entity("SalegaTech.Domain.Entities.FinancingSimulation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("NumberOfInstallments")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SimulationCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("SimulationDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SimulationCode")
                        .IsUnique();

                    b.ToTable("FinancingSimulations", (string)null);
                });

            modelBuilder.Entity("SalegaTech.Domain.Entities.Partner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Partners", (string)null);
                });

            modelBuilder.Entity("SalegaTech.Domain.Entities.CreditFile", b =>
                {
                    b.HasOne("SalegaTech.Domain.Entities.Partner", "Partner")
                        .WithMany()
                        .HasForeignKey("PartnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SalegaTech.Domain.Entities.FinancingSimulation", "Simulation")
                        .WithMany()
                        .HasForeignKey("SimulationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Partner");

                    b.Navigation("Simulation");
                });

            modelBuilder.Entity("SalegaTech.Domain.Entities.FinancingSimulation", b =>
                {
                    b.OwnsOne("SalegaTech.Domain.ValueObjects.Money", "Amount", b1 =>
                        {
                            b1.Property<Guid>("FinancingSimulationId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("TEXT")
                                .HasColumnName("Amount_Currency");

                            b1.Property<decimal>("Value")
                                .HasPrecision(18, 2)
                                .HasColumnType("TEXT")
                                .HasColumnName("Amount_Value");

                            b1.HasKey("FinancingSimulationId");

                            b1.ToTable("FinancingSimulations");

                            b1.WithOwner()
                                .HasForeignKey("FinancingSimulationId");
                        });

                    b.OwnsOne("SalegaTech.Domain.ValueObjects.Money", "MonthlyPayment", b1 =>
                        {
                            b1.Property<Guid>("FinancingSimulationId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("TEXT")
                                .HasColumnName("MonthlyPayment_Currency");

                            b1.Property<decimal>("Value")
                                .HasPrecision(18, 2)
                                .HasColumnType("TEXT")
                                .HasColumnName("MonthlyPayment_Value");

                            b1.HasKey("FinancingSimulationId");

                            b1.ToTable("FinancingSimulations");

                            b1.WithOwner()
                                .HasForeignKey("FinancingSimulationId");
                        });

                    b.OwnsOne("SalegaTech.Domain.ValueObjects.Money", "ResidualValue", b1 =>
                        {
                            b1.Property<Guid>("FinancingSimulationId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("TEXT")
                                .HasColumnName("ResidualValue_Currency");

                            b1.Property<decimal>("Value")
                                .HasPrecision(18, 2)
                                .HasColumnType("TEXT")
                                .HasColumnName("ResidualValue_Value");

                            b1.HasKey("FinancingSimulationId");

                            b1.ToTable("FinancingSimulations");

                            b1.WithOwner()
                                .HasForeignKey("FinancingSimulationId");
                        });

                    b.OwnsOne("SalegaTech.Domain.ValueObjects.InterestRate", "Rate", b1 =>
                        {
                            b1.Property<Guid>("FinancingSimulationId")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("ValueAsPercentage")
                                .HasPrecision(5, 2)
                                .HasColumnType("TEXT")
                                .HasColumnName("Rate_ValueAsPercentage");

                            b1.HasKey("FinancingSimulationId");

                            b1.ToTable("FinancingSimulations");

                            b1.WithOwner()
                                .HasForeignKey("FinancingSimulationId");
                        });

                    b.Navigation("Amount")
                        .IsRequired();

                    b.Navigation("MonthlyPayment")
                        .IsRequired();

                    b.Navigation("Rate")
                        .IsRequired();

                    b.Navigation("ResidualValue")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
