// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace SalegaTech.Legacy.Persistance.Migrations
{
    [DbContext(typeof(LegacyDbContext))]
    partial class LegacyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("SalegaTech.Legacy.Persistence.LegacyPartnerRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CDE_PARTENAIRE")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("LIB_PARTENAIRE")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CDE_PARTENAIRE")
                        .IsUnique();

                    b.ToTable("TBL_PARTENAIRE", (string)null);
                });

            modelBuilder.Entity("SalegaTech.Legacy.Persistence.LegacySimulationRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CDE_DOSSIER")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("CDE_PARTENAIRE")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<int>("CDE_STATUT")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CDE_TYPE")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DT_SIMULATION")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MNT_FINANCEMENT")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MNT_MENSUALITE")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MNT_VR")
                        .HasColumnType("TEXT");

                    b.Property<string>("MSG_ERREUR")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("NBR_ECHEANCES")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TX_INTERET")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CDE_DOSSIER")
                        .IsUnique();

                    b.ToTable("TBL_SIMULATION", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
